class ApiMsgConstant {
  static String getResponseMessage(String code) {
    const Map<String, String> statusCode = {
      "100": "Header is missing",
      "101": "Device type not allowed",
      "102": "Invalid Api Key",
      "103": "A token is required for authentication",
      "104": "Your session is expired please login again",
      "106": "Unauthorized Access",
      "109": "Membership have been remove or expired",
      "110": "User status is inactive",
      "200": "Success",
      "500": "Internal server error.",
      "111": "Invalid login credentials.",
      "112": "Email exist",
      "113": "Token invalid or expired",
      "114": "Brand name exist",
      "115": "Invalid verification code",
      "116": "Failed to send email",
      "117": "Invalid brand id",
      "118": "Invalid brand picture size",
      "119": "Invalid brand file extension",
      "120": "Invalid app logo picture size",
      "121": "Invalid app logo file extension",
      "122": "App logo required",
      "123": "Country id is required",
      "124": "Invalid group id",
      "125": "Email and phone number exist",
      "126": "Invalid member id",
      "127": "Invalid member picture size",
      "128": "Invalid member file extension",
      "129": "Group name exist",
      "130": "Invalid personal bests object",
      "131": "Invalid brands object",
      "132": "Member limit exceeded",
      "133": "The group is already in use, you can't perform a delete operation.",
      "134": "Phone number exist",
      "135": "Profile picture required",
      "136": "Invalid event id",
      "137": "Invalid event picture size",
      "138": "Invalid event file extension",
      "139": "Invalid result distance JSON object",
      "140": "Invalid key in result distance JSON object",
      "141": "Event name already exist",
      "142": "Member is inactive",
      "143": "Account not found",
      "144": "Invalid personal bests JSON object",
      "145": "Invalid brands JSON object",
      "146": "Event gallery required",
      "147": "Invalid event gallery picture size",
      "148": "Invalid event gallery file extension",
      "149": "Brands field is required",
      "150": "Invalid poll answers JSON object",
      "151": "Invalid key in poll answers JSON object",
      "152": "Duplicate poll answer found",
      "153": "Number of poll answer can be maximum 10",
      "154": "Invalid training groups JSON object",
      "155": "Already a member of this club",
      "156": "Member invitation is already sent",
      "157": "Invalid event result id",
      "158": "Inviation expired",
      "159": "Action already taken",
      "160": "Invalid distance id",
      "161": "Event result already exist",
      "162": "Invalid workout type id",
      "163": "Workout type exist",
      "164": "The workout type is already in use, you can't perform a delete operation.",
      "165": "Failed to send sms",
      "166": "Workout title exist",
      "167": "Invalid workout id",
      "168": "Invalid workout picture size",
      "169": "Invalid workout picture file extension",
      "170": "The workout is already in use, you can't perform a delete operation.",
      "171": "Route name exist",
      "172": "Invalid route picture size",
      "173": "Invalid route picture file extension",
      "174": "Invalid route id",
      "175": "The route is already in use, you can't perform a delete operation.",
      "176": "Invalid answer id",
      "177": "News gallery required",
      "178": "Invalid news gallery picture size",
      "179": "Invalid news gallery file extension",
      "180": "Invalid news id",
      "181": "Invalid training id",
      "182": "Invalid news picture size",
      "183": "Invalid news file extension",
      "184": "News title exist",
      "186": "Poll vote exist",
      "187": "Invalid question id",
      "188": "Poll vote not exist",
      "189": "Invalid event gallery image id",
      "190": "Invalid news gallery image id",
      "191": "Invalid date format",
      "192": "Invalid image sequence JSON object",
      "193": "Invalid key in image sequence object",
      "194": "Invalid news poll vote id",
      "195": "Cannot add more than one group",
      "196": "Cannot add more than three images",
      "197": "Invalid distance id",
      "198": "Invalid personal best id",
      "199": "This member is not a part of this group",
      "201": "This member is not a part of this brand",
      "202": "Invalid workout log id",
      "203": "Old password not matched",
      "204": "Content is not available",
      "205": "invalid workout image remove object",
      "206": "membership exit failed",
      "207": "Invalid logbook id",
      "208": "This workout type already used in user workout list due to can't delete it",
      "209": "The club is inactive, Please contact the club",
      "210": "Twitter request token failed",
      "211": "Twitter access token failed",
      "212": "Membership no longer exist",
      "213": "Can not forgot password for a social account",
      "214": "No repeating days found between your start and end date",
      "215": "Object is not available for this action please refresh the screen",
      "216": "Invalid phone verification code"
    };
    return statusCode[code] ?? "Unknown error code"; // Use null-aware operator
  }
}